#ifndef DOCKERFRAME_GLOBAL_H
#define DOCKERFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DOCKERFRAME_LIBRARY)
#  define DOCKERFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DOCKERFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DOCKERFRAME_GLOBAL_H
